export const FLAT_REGIONS = [
  "Africa",
  "Americas",
  "Antarctic",
  "Asia",
  "Europe",
  "Oceania",
];

export const FLAT_SUBREGIONS = [
  "Antarctic",
  "Australia and New Zealand",
  "Caribbean",
  "Central America",
  "Central Asia",
  "Central Europe",
  "Eastern Africa",
  "Eastern Asia",
  "Eastern Europe",
  "Melanesia",
  "Micronesia",
  "Middle Africa",
  "North America",
  "Northern Africa",
  "Northern Europe",
  "Polynesia",
  "South America",
  "South-Eastern Asia",
  "Southeast Europe",
  "Southern Africa",
  "Southern Asia",
  "Southern Europe",
  "Western Africa",
  "Western Asia",
  "Western Europe",
];

export const FLAT_COUNTRIES = [
  "Iceland",
  "Spain",
  "Iraq",
  "Malawi",
  "Hong Kong",
  "Malta",
  "Paraguay",
  "Djibouti",
  "Madagascar",
  "Nepal",
  "San Marino",
  "Netherlands",
  "Greenland",
  "Norway",
  "Tuvalu",
  "Lebanon",
  "Burkina Faso",
  "Cape Verde",
  "Gibraltar",
  "Algeria",
  "Georgia",
  "Mongolia",
  "Iran",
  "Tokelau",
  "Singapore",
  "French Guiana",
  "Martinique",
  "British Virgin Islands",
  "Nicaragua",
  "Moldova",
  "Yemen",
  "Gambia",
  "Kyrgyzstan",
  "Cuba",
  "Eritrea",
  "Svalbard and Jan Mayen",
  "El Salvador",
  "Timor-Leste",
  "South Korea",
  "Mali",
  "Turks and Caicos Islands",
  "Ghana",
  "Egypt",
  "Gabon",
  "Togo",
  "Taiwan",
  "Cook Islands",
  "Eswatini",
  "Oman",
  "Central African Republic",
  "Italy",
  "Uruguay",
  "Bahamas",
  "Brazil",
  "Myanmar",
  "Vatican City",
  "Sweden",
  "Vietnam",
  "Estonia",
  "Guinea-Bissau",
  "Aruba",
  "Palestine",
  "Peru",
  "Antigua and Barbuda",
  "Heard Island and McDonald Islands",
  "Burundi",
  "Jordan",
  "Pitcairn Islands",
  "Guatemala",
  "French Polynesia",
  "South Georgia",
  "Laos",
  "Sierra Leone",
  "India",
  "British Indian Ocean Territory",
  "Jamaica",
  "North Macedonia",
  "Canada",
  "Guam",
  "Norfolk Island",
  "Saint Kitts and Nevis",
  "Grenada",
  "Liberia",
  "United States",
  "Bahrain",
  "Germany",
  "Bermuda",
  "Malaysia",
  "Kiribati",
  "Ukraine",
  "Faroe Islands",
  "Afghanistan",
  "São Tomé and Príncipe",
  "Kuwait",
  "Poland",
  "Vanuatu",
  "Comoros",
  "American Samoa",
  "Niue",
  "China",
  "Western Sahara",
  "Panama",
  "Solomon Islands",
  "Costa Rica",
  "Papua New Guinea",
  "Japan",
  "South Sudan",
  "Marshall Islands",
  "Monaco",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Sint Maarten",
  "Venezuela",
  "Micronesia",
  "Montserrat",
  "Thailand",
  "Bouvet Island",
  "Anguilla",
  "Philippines",
  "New Zealand",
  "Saint Barthélemy",
  "Brunei",
  "Slovakia",
  "Republic of the Congo",
  "Wallis and Futuna",
  "New Caledonia",
  "Montenegro",
  "French Southern and Antarctic Lands",
  "Finland",
  "Liechtenstein",
  "Colombia",
  "Andorra",
  "Belize",
  "Bolivia",
  "Niger",
  "Russia",
  "Caribbean Netherlands",
  "Tanzania",
  "Zimbabwe",
  "Antarctica",
  "Azerbaijan",
  "Mauritius",
  "Armenia",
  "Czechia",
  "Haiti",
  "Sri Lanka",
  "Albania",
  "Morocco",
  "United States Virgin Islands",
  "Syria",
  "Bhutan",
  "Jersey",
  "Senegal",
  "Réunion",
  "Tunisia",
  "Switzerland",
  "Saint Pierre and Miquelon",
  "Luxembourg",
  "Samoa",
  "Austria",
  "Turkey",
  "Latvia",
  "United Arab Emirates",
  "Bosnia and Herzegovina",
  "Botswana",
  "Guernsey",
  "Seychelles",
  "Angola",
  "Australia",
  "Qatar",
  "Slovenia",
  "Namibia",
  "Saint Martin",
  "Equatorial Guinea",
  "Christmas Island",
  "Cambodia",
  "Guinea",
  "Dominica",
  "Cyprus",
  "Israel",
  "Ivory Coast",
  "Uzbekistan",
  "Zambia",
  "Somalia",
  "Bulgaria",
  "Rwanda",
  "Belgium",
  "Guyana",
  "Kosovo",
  "Mexico",
  "Denmark",
  "DR Congo",
  "Curaçao",
  "Ethiopia",
  "Macau",
  "Pakistan",
  "Indonesia",
  "Nauru",
  "Northern Mariana Islands",
  "United Kingdom",
  "Argentina",
  "Cameroon",
  "Romania",
  "Uganda",
  "France",
  "Suriname",
  "Maldives",
  "Fiji",
  "Greece",
  "Trinidad and Tobago",
  "Mauritania",
  "Tonga",
  "Chile",
  "Benin",
  "Sudan",
  "Chad",
  "Lesotho",
  "Saint Lucia",
  "Falkland Islands",
  "Lithuania",
  "Mozambique",
  "Tajikistan",
  "Cocos (Keeling) Islands",
  "North Korea",
  "Serbia",
  "United States Minor Outlying Islands",
  "Puerto Rico",
  "Honduras",
  "Kenya",
  "Portugal",
  "Belarus",
  "Dominican Republic",
  "Mayotte",
  "Palau",
  "Saudi Arabia",
  "Bangladesh",
  "Barbados",
  "Isle of Man",
  "Kazakhstan",
  "Libya",
  "Cayman Islands",
  "Nigeria",
  "Ireland",
  "South Africa",
  "Ecuador",
  "Guadeloupe",
  "Åland Islands",
  "Saint Vincent and the Grenadines",
  "Croatia",
  "Hungary",
  "Turkmenistan",
];

export const COUNTRIES_BY_REGION = {
  africa: [
    "Malawi",
    "Djibouti",
    "Madagascar",
    "Burkina Faso",
    "Cape Verde",
    "Algeria",
    "Gambia",
    "Eritrea",
    "Mali",
    "Ghana",
    "Egypt",
    "Gabon",
    "Togo",
    "Eswatini",
    "Central African Republic",
    "Guinea-Bissau",
    "Burundi",
    "Sierra Leone",
    "British Indian Ocean Territory",
    "Liberia",
    "São Tomé and Príncipe",
    "Comoros",
    "Western Sahara",
    "South Sudan",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Republic of the Congo",
    "Niger",
    "Tanzania",
    "Zimbabwe",
    "Mauritius",
    "Morocco",
    "Senegal",
    "Réunion",
    "Tunisia",
    "Botswana",
    "Seychelles",
    "Angola",
    "Namibia",
    "Equatorial Guinea",
    "Guinea",
    "Ivory Coast",
    "Zambia",
    "Somalia",
    "Rwanda",
    "DR Congo",
    "Ethiopia",
    "Cameroon",
    "Uganda",
    "Mauritania",
    "Benin",
    "Sudan",
    "Chad",
    "Lesotho",
    "Mozambique",
    "Kenya",
    "Mayotte",
    "Libya",
    "Nigeria",
    "South Africa",
  ],
  americas: [
    "Paraguay",
    "Greenland",
    "French Guiana",
    "Martinique",
    "British Virgin Islands",
    "Nicaragua",
    "Cuba",
    "El Salvador",
    "Turks and Caicos Islands",
    "Uruguay",
    "Bahamas",
    "Brazil",
    "Aruba",
    "Peru",
    "Antigua and Barbuda",
    "Guatemala",
    "Jamaica",
    "Canada",
    "Saint Kitts and Nevis",
    "Grenada",
    "United States",
    "Bermuda",
    "Panama",
    "Costa Rica",
    "Sint Maarten",
    "Venezuela",
    "Montserrat",
    "Anguilla",
    "Saint Barthélemy",
    "Colombia",
    "Belize",
    "Bolivia",
    "Caribbean Netherlands",
    "Haiti",
    "United States Virgin Islands",
    "Saint Pierre and Miquelon",
    "Saint Martin",
    "Dominica",
    "Guyana",
    "Mexico",
    "Curaçao",
    "Argentina",
    "Suriname",
    "Trinidad and Tobago",
    "Chile",
    "Saint Lucia",
    "Falkland Islands",
    "United States Minor Outlying Islands",
    "Puerto Rico",
    "Honduras",
    "Dominican Republic",
    "Barbados",
    "Cayman Islands",
    "Ecuador",
    "Guadeloupe",
    "Saint Vincent and the Grenadines",
  ],
  antarctic: [
    "Heard Island and McDonald Islands",
    "South Georgia",
    "Bouvet Island",
    "French Southern and Antarctic Lands",
    "Antarctica",
  ],
  asia: [
    "Iraq",
    "Hong Kong",
    "Nepal",
    "Lebanon",
    "Georgia",
    "Mongolia",
    "Iran",
    "Singapore",
    "Yemen",
    "Kyrgyzstan",
    "Timor-Leste",
    "South Korea",
    "Taiwan",
    "Oman",
    "Myanmar",
    "Vietnam",
    "Palestine",
    "Jordan",
    "Laos",
    "India",
    "Bahrain",
    "Malaysia",
    "Afghanistan",
    "Kuwait",
    "China",
    "Japan",
    "Thailand",
    "Philippines",
    "Brunei",
    "Azerbaijan",
    "Armenia",
    "Sri Lanka",
    "Syria",
    "Bhutan",
    "Turkey",
    "United Arab Emirates",
    "Qatar",
    "Cambodia",
    "Israel",
    "Uzbekistan",
    "Macau",
    "Pakistan",
    "Indonesia",
    "Maldives",
    "Tajikistan",
    "North Korea",
    "Saudi Arabia",
    "Bangladesh",
    "Kazakhstan",
    "Turkmenistan",
  ],
  europe: [
    "Iceland",
    "Spain",
    "Malta",
    "San Marino",
    "Netherlands",
    "Norway",
    "Gibraltar",
    "Moldova",
    "Svalbard and Jan Mayen",
    "Italy",
    "Vatican City",
    "Sweden",
    "Estonia",
    "North Macedonia",
    "Germany",
    "Ukraine",
    "Faroe Islands",
    "Poland",
    "Monaco",
    "Slovakia",
    "Montenegro",
    "Finland",
    "Liechtenstein",
    "Andorra",
    "Russia",
    "Czechia",
    "Albania",
    "Jersey",
    "Switzerland",
    "Luxembourg",
    "Austria",
    "Latvia",
    "Bosnia and Herzegovina",
    "Guernsey",
    "Slovenia",
    "Cyprus",
    "Bulgaria",
    "Belgium",
    "Kosovo",
    "Denmark",
    "United Kingdom",
    "Romania",
    "France",
    "Greece",
    "Lithuania",
    "Serbia",
    "Portugal",
    "Belarus",
    "Isle of Man",
    "Ireland",
    "Åland Islands",
    "Croatia",
    "Hungary",
  ],
  oceania: [
    "Tuvalu",
    "Tokelau",
    "Cook Islands",
    "Pitcairn Islands",
    "French Polynesia",
    "Guam",
    "Norfolk Island",
    "Kiribati",
    "Vanuatu",
    "American Samoa",
    "Niue",
    "Solomon Islands",
    "Papua New Guinea",
    "Marshall Islands",
    "Micronesia",
    "New Zealand",
    "Wallis and Futuna",
    "New Caledonia",
    "Samoa",
    "Australia",
    "Christmas Island",
    "Nauru",
    "Northern Mariana Islands",
    "Fiji",
    "Tonga",
    "Cocos (Keeling) Islands",
    "Palau",
  ],
};
